# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kacper Dębowski
email: kdebowski93@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal blog where I'm mostly wrong about programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kdebowski.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kdebowski
github_username:  sc0
logo: "/images/kacper-debowski-mugshot.jpg"
locale: "en-US"

read_time: true
words_per_minute: 200

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple 
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

category_archive_path: "/categories/#"
tag_archive_path: "/tag/#"

# author:
#   name: Kacper Dębowski
#   twitter: kdebowski
#   picture: /images/kacper-debowski-mugshot.jpg

footer_links:
  - title: Twitter
    url: https://twitter.com/kdebowski93
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/sc0
    icon: fab fa-github-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus:
  shortname: kdebowski

google_analytics: UA-120234627-1